import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster 
          theme="dark" 
          toastOptions={{
            style: {
              background: 'rgb(15 23 42 / 0.9)', // slate-900/90
              borderColor: 'rgb(30 41 59)', // slate-800
              color: 'rgb(241 245 249)', // slate-100
            },
            className: 'backdrop-blur-sm'
          }}
        />
      </body>
    </html>
  );
}
